app:
  secret: 53e3cf11-85c8-4601-a9de-fac3b6420f3c
  keycloak:
    userid: admin
    password: PostAdm@ssw0rd229
  image-upload-path: /root/skill-zag/micro-services/image/
  achievement-upload-path: /root/skill-zag/micro-services/achivement/
  user:
    url: http://103.241.145.14:8080/auth/admin/realms/skillzag-realm/users/
keycloak:
  auth-server-url: http://103.241.145.14:8080/auth
  bearer-only: true
  realm: skillzag-realm
  resource: skillzag-app
  ssl-required: external
  use-resource-role-mappings: true
server:
  connection-timeout: 6000
  port: 8061
  servlet:
    context-path: /skillzag/auth

logging:
  file: ./logs/skill-zag-login-service.log
  level:
    org:
      springframework: INFO
    root: INFO
spring:
  servlet:
    multipart:
      enabled: true
      max-request-size: 15MB
      max-file-size: 10MB