app:
  secret: 231b23cc-1991-4f69-ab0e-b30264532667
  keycloak:
    userid: admin
    password: admin
  user:
    url: http://localhost:8080/auth/admin/realms/skillzag-realm/users/
keycloak:
  auth-server-url: http://localhost:8080/auth
  bearer-only: true
  realm: skillzag-realm
  resource: skillzag-app
  ssl-required: external
  use-resource-role-mappings: true
server:
  connection-timeout: 6000
  port: 8055
  servlet:
    context-path: /skillzag/auth

logging:
  file: ./logs/skill-zag-login-service.log
  level:
    org:
      springframework: INFO
    root: INFO