apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: skill-zag-login-service-dev
  namespace: authentication
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: skill-zag-login-service-dev
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80

